<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Course;
use Illuminate\Database\Seeder;

/**
 * Seeds the category tree plus a starter catalog of real 10 Minute School courses.
 * Affiliate links point at the public product pages; replace them with your own
 * affiliate links from affiliation.10minuteschool.com in the admin panel.
 */
class CatalogSeeder extends Seeder
{
    public function run(): void
    {
        $categories = collect([
            ['group' => 'academic', 'name' => 'ক্লাস ১-৫', 'slug' => 'class-1-5', 'tagline' => 'কিডস ইংলিশ ও প্রাথমিক ভিত্তি', 'class_min' => 1, 'class_max' => 5, 'sort_order' => 1],
            ['group' => 'academic', 'name' => 'ক্লাস ৬', 'slug' => 'class-6', 'tagline' => '৬ষ্ঠ শ্রেণির অনলাইন ব্যাচ', 'class_min' => 6, 'class_max' => 6, 'sort_order' => 2],
            ['group' => 'academic', 'name' => 'ক্লাস ৭', 'slug' => 'class-7', 'tagline' => '৭ম শ্রেণির অনলাইন ব্যাচ', 'class_min' => 7, 'class_max' => 7, 'sort_order' => 3],
            ['group' => 'academic', 'name' => 'ক্লাস ৮', 'slug' => 'class-8', 'tagline' => '৮ম শ্রেণির অনলাইন ব্যাচ', 'class_min' => 8, 'class_max' => 8, 'sort_order' => 4],
            ['group' => 'academic', 'name' => 'ক্লাস ৯-১০ (SSC)', 'slug' => 'ssc', 'tagline' => 'SSC বোর্ড পরীক্ষার প্রস্তুতি', 'class_min' => 9, 'class_max' => 10, 'sort_order' => 5],
            ['group' => 'academic', 'name' => 'ক্লাস ১১-১২ (HSC)', 'slug' => 'hsc', 'tagline' => 'বিষয়ভিত্তিক HSC অনলাইন ব্যাচ', 'class_min' => 11, 'class_max' => 12, 'sort_order' => 6],
            ['group' => 'academic', 'name' => 'ভর্তি পরীক্ষা', 'slug' => 'admission', 'tagline' => 'বিশ্ববিদ্যালয় ভর্তি পরীক্ষার প্রস্তুতি', 'sort_order' => 7],
            ['group' => 'skills', 'name' => 'ভাষা শিক্ষা', 'slug' => 'language', 'tagline' => 'ইংরেজি, IELTS, আরবি ও আরও', 'sort_order' => 10],
            ['group' => 'skills', 'name' => 'ফ্রিল্যান্সিং', 'slug' => 'freelancing', 'tagline' => 'সত্যিকারের স্কিল দিয়ে অনলাইনে আয়', 'sort_order' => 11],
            ['group' => 'skills', 'name' => 'স্কিলস ও আইটি', 'slug' => 'skills-it', 'tagline' => 'প্রোগ্রামিং ও কম্পিউটার স্কিল', 'sort_order' => 12],
            ['group' => 'skills', 'name' => 'ডিজাইন ও ক্রিয়েটিভ', 'slug' => 'design', 'tagline' => 'গ্রাফিক ডিজাইন, ভিডিও ও ফটোগ্রাফি', 'sort_order' => 13],
            ['group' => 'skills', 'name' => 'ক্যারিয়ার রেডিনেস', 'slug' => 'career', 'tagline' => 'কমিউনিকেশন, CV ও ইন্টারভিউ', 'sort_order' => 14],
            ['group' => 'skills', 'name' => 'প্রফেশনাল', 'slug' => 'professional', 'tagline' => 'লিডারশিপ, নেগোসিয়েশন ও মানি ম্যানেজমেন্ট', 'sort_order' => 15],
            ['group' => 'skills', 'name' => 'বান্ডেল', 'slug' => 'bundles', 'tagline' => 'কয়েকটি কোর্স, একটি দামে', 'sort_order' => 16],
        ])->mapWithKeys(fn ($c) => [$c['slug'] => Category::updateOrCreate(['slug' => $c['slug']], $c)]);

        $cdn = 'https://cdn.10minuteschool.com/images/';
        $site = 'https://10minuteschool.com/product/';
        $tms = 'টেন মিনিট স্কুল';

        $courses = [
            // ভাষা শিক্ষা
            ['language', 'IELTS Course', 'Munzereen Shahid', 3500, 5000, false, true, 'বেস্ট সেলার',
                'Listening, Reading, Writing ও Speaking, IELTS-এর চারটি মডিউলের সম্পূর্ণ প্রস্তুতি। ব্যান্ড স্কোর বাড়ানোর কৌশল আর ফুল মক টেস্টসহ।',
                ['চারটি মডিউলের কৌশল', 'Writing Task 1 ও Task 2 টেমপ্লেট', 'মডেল উত্তরসহ Speaking প্র্যাকটিস', 'উত্তরসহ ফুল-লেংথ মক টেস্ট'],
                $site.'ielts-course/', $cdn.'thumbnails/IELTS_new_16_9.png'],
            ['language', 'ঘরে বসে Spoken English', 'Munzereen Shahid', 1950, 2500, false, true, null,
                'ঘরে বসেই আত্মবিশ্বাসের সাথে ইংরেজি বলা শিখুন। দৈনন্দিন কথোপকথন, উচ্চারণ আর ভোকাবুলারি, সহজ বাংলায়।',
                ['দৈনন্দিন কথোপকথন প্র্যাকটিস', 'উচ্চারণ ও ফ্লুয়েন্সি ড্রিল', 'সাধারণ ভুল ও তার সমাধান', 'রেকর্ডেড লেকচারে লাইফটাইম অ্যাক্সেস'],
                $site.'ghore-boshe-spoken-english/', $cdn.'thumbnails/skills/ghore-boshe-Spoken-English-course-thumbnail-by-Munzereen-Shahid-16x9.jpg'],
            ['language', 'IELTS LIVE Batch', 'Zawad Hasan Adib ও টিম', 8000, null, false, false, 'লাইভ ব্যাচ',
                'লাইভ অনলাইন IELTS ক্লাস, যেখানে ইন্সট্রাক্টর আপনার Writing ও Speaking-এ ফিডব্যাক দেবেন। সাথে মক টেস্ট ও ডাউট সল্ভিং সেশন।',
                ['এক্সপার্ট ইন্সট্রাক্টরের লাইভ ক্লাস', 'Writing ও Speaking-এ ব্যক্তিগত ফিডব্যাক', 'নিয়মিত মক টেস্ট', 'ডাউট সল্ভিং সাপোর্ট'],
                $site.'ielts-live-batch/', $cdn.'thumbnails/batch-12-ielts-live-batch-thumbnails.jpg'],
            ['language', 'Spoken English Junior', $tms, null, null, false, false, 'লাইভ ব্যাচ',
                'ক্লাস ৬-১০ এর শিক্ষার্থীদের জন্য তৈরি স্পোকেন ইংলিশ প্রোগ্রাম। লাইভ প্র্যাকটিস সেশন আর বয়স উপযোগী টপিক।',
                ['লাইভ কথোপকথন প্র্যাকটিস', 'প্রসঙ্গসহ গ্রামার', 'আত্মবিশ্বাস বাড়ানোর অ্যাক্টিভিটি'],
                $site.'spoken-english-junior/', $cdn.'thumbnails/spoken-english-junior-new-thumbnail.jpg'],
            ['language', '২৪ ঘণ্টায় কোরআন শিখি', 'শাইখ মুহাম্মাদ জামাল উদ্দীন', 1250, null, false, false, null,
                'তাজবীদসহ সহিহভাবে কোরআন পড়া শিখুন, ধাপে ধাপে, বাংলায়।',
                ['আরবি হরফ ও উচ্চারণ', 'উদাহরণসহ তাজবীদের নিয়ম', 'গাইডেড রিডিং প্র্যাকটিস'],
                $site.'easy-quran-reading/', $cdn.'thumbnails/skills/24-ghontay-quran-shikhi-course-thumbnail-by-sheikh-mohammad-jamal-uddin-16x9.jpg'],
            // ফ্রিল্যান্সিং
            ['freelancing', 'WordPress দিয়ে Freelancing', 'Asaduzzaman Asad', 2500, null, false, false, null,
                'WordPress দিয়ে ওয়েবসাইট বানান আর ফ্রিল্যান্স ক্লায়েন্টের কাজ শুরু করুন। থিম, প্লাগইন, কাস্টমাইজেশন ও মার্কেটপ্লেস প্রোফাইল।',
                ['WordPress সেটআপ ও কাস্টমাইজেশন', 'জনপ্রিয় পেজ বিল্ডার', 'ফ্রিল্যান্স প্রোফাইল তৈরি', 'ক্লায়েন্ট খোঁজা ও কাজ সামলানো'],
                $site.'wordpress-course/', $cdn.'thumbnails/skills_new/wordpress-course-thumbnail.jpg'],
            ['freelancing', 'Freelancing এর হাতেখড়ি', 'Ahsan Mahbub Yeaman', 0, null, true, false, null,
                'ফ্রিল্যান্সিংয়ের ফ্রি পরিচিতি কোর্স: কোন স্কিল বিক্রি হয়, মার্কেটপ্লেস কীভাবে কাজ করে আর প্রথম কাজটি কীভাবে পাবেন।',
                ['কোন স্কিল বেছে নেবেন', 'Fiverr ও Upwork কীভাবে কাজ করে', 'কাজ পাওয়ার মতো প্রোফাইল লেখা'],
                $site.'freelancing-er-hatekhori/', $cdn.'thumbnails/skills/freelancing-er-hatekhori-free-course-thumbnail.jpg'],
            ['freelancing', 'Learn Graphic Design', 'A.S.M. Arifuzzaman', 2500, null, false, false, null,
                'ফ্রিল্যান্সারদের জন্য প্রফেশনাল গ্রাফিক ডিজাইন: Photoshop, Illustrator আর সত্যিকারের ক্লায়েন্ট প্রজেক্ট।',
                ['Photoshop ও Illustrator ওয়ার্কফ্লো', 'লোগো, ব্যানার ও সোশ্যাল মিডিয়া ডিজাইন', 'পোর্টফোলিও ও মার্কেটপ্লেস সেটআপ'],
                $site.'professional-graphic-design-course/', $cdn.'thumbnails/skills/graphics-design-course-thumbnail.jpg'],
            // স্কিলস ও আইটি
            ['skills-it', 'Python দিয়ে Programming', 'Niamul Hasan', 2500, null, false, true, null,
                'একদম শূন্য থেকে Python প্রোগ্রামিং শুরু করুন। ভেরিয়েবল, লুপ, ফাংশন, ফাইল আর ছোট ছোট প্রজেক্ট, সব বাংলায়।',
                ['Python বেসিক থেকে ইন্টারমিডিয়েট', 'হাতে-কলমে কোডিং এক্সারসাইজ', 'প্র্যাকটিসের জন্য মিনি প্রজেক্ট', 'কোর্স শেষে সার্টিফিকেট'],
                $site.'python-programming-course/', $cdn.'thumbnails/python-course-in-bangladesh-thumbnail-new.jpg'],
            ['skills-it', 'সহজ ভাষায় C Programming', 'Monjurul Ahsan Nobel', 0, null, true, false, null,
                'বিগিনার আর বিশ্ববিদ্যালয়ের কোর্সের প্রস্তুতি নেওয়া শিক্ষার্থীদের জন্য ফ্রি C প্রোগ্রামিং কোর্স।',
                ['C সিনট্যাক্স ও ডেটা টাইপ', 'লুপ, অ্যারে ও ফাংশন', 'সহজভাবে পয়েন্টার'],
                $site.'c-programming-course/', $cdn.'quiz/course_thumbnail/c-programming-free-course-thumbnail.jpg'],
            // ডিজাইন
            ['design', 'Graphic Design এর হাতেখড়ি', 'Ahsan Mahbub Yeaman ও টিম', 0, null, true, false, null,
                'গ্রাফিক ডিজাইনের মূল ধারণা আর টুল নিয়ে ফ্রি স্টার্টার কোর্স।',
                ['ডিজাইনের মূলনীতি', 'Photoshop দিয়ে শুরু', 'সহজ প্রজেক্ট ওয়াকথ্রু'],
                $site.'free-graphic-design-course/', $cdn.'thumbnails/free-graphic-design-online-course-thumbnail.jpg'],
            ['design', 'Basic Photography Course', 'Prito Reza', 1950, null, false, false, null,
                'দেশের অন্যতম পরিচিত ফটোগ্রাফারের কাছে কম্পোজিশন, আলো আর ক্যামেরা সেটিংস শিখুন।',
                ['ক্যামেরা ও এক্সপোজার বেসিক', 'কম্পোজিশন ও ফ্রেমিং', 'পোর্ট্রেট ও ল্যান্ডস্কেপ শুট'],
                $site.'photography-course/', $cdn.'thumbnails/photography-course-in-bangladesh-thumbnail.jpg'],
            ['design', 'Video Making', 'Sadman Sadik', 1250, null, false, false, null,
                'হাতে থাকা গিয়ার দিয়েই YouTube আর সোশ্যাল মিডিয়ার জন্য ভিডিও প্ল্যান, শুট ও এডিট করুন।',
                ['স্টোরিবোর্ড ও স্ক্রিপ্ট', 'ফোন বা ক্যামেরায় শুটিং', 'এডিটিং ও পাবলিশিং'],
                $site.'video-making/', $cdn.'thumbnails/skills/Video-Making-course-thumbnail-by-Sadman-Sadik-16x9.jpg'],
            ['design', 'মোবাইল দিয়ে Graphic Designing', 'Sadman Sadik', 0, null, true, false, null,
                'শুধু মোবাইল ফোন দিয়ে পোস্টার ও সোশ্যাল মিডিয়া গ্রাফিক্স ডিজাইনের ফ্রি কোর্স।',
                ['মোবাইল ডিজাইন অ্যাপ', 'সোশ্যাল মিডিয়া পোস্ট টেমপ্লেট', 'টাইপোগ্রাফি বেসিক'],
                $site.'graphic-design-with-mobile/', $cdn.'thumbnails/skills/mobile-diye-graphic-designing-course-thumbnail-by-sadman-sadik-16x9.jpg'],
            ['design', 'Graphic Designing with Photoshop', 'Sadman Sadik', 0, null, true, false, null,
                'ডিজাইনের কাজে Adobe Photoshop-এর ফ্রি, হাতে-কলমে পরিচিতি।',
                ['Photoshop ইন্টারফেস ও টুল', 'লেয়ার, মাস্ক ও ইফেক্ট', 'প্র্যাকটিস প্রজেক্ট'],
                $site.'graphic-designing-with-photoshop/', $cdn.'thumbnails/skills/graphic-design-with-photoshop-course-thumbnail-by-sadman-sadik-16x9.jpg'],
            ['design', 'Adobe Illustrator', 'Mohammad Yeasir', 0, null, true, false, null,
                'Adobe Illustrator দিয়ে ভেক্টর ডিজাইনের ফ্রি কোর্স: লোগো, আইকন ও ইলাস্ট্রেশন।',
                ['পেন টুল ও শেপ', 'লোগো ডিজাইন ওয়ার্কফ্লো', 'প্রিন্ট ও ওয়েবের জন্য এক্সপোর্ট'],
                $site.'adobe-illustrator/', $cdn.'thumbnails/skills/adobe-illustrator-course-thumbnail-by-mohammad-yeasir-16x9.jpg'],
            // ক্যারিয়ার
            ['career', 'Communication Masterclass by Tahsan Khan', 'Tahsan Khan', 1250, null, false, true, null,
                'ইন্টারভিউ, প্রেজেন্টেশন আর প্রতিদিনের প্রফেশনাল জীবনে স্পষ্ট ও আত্মবিশ্বাসী কথা বলা শিখুন।',
                ['কথা গুছিয়ে বলা', 'বডি ল্যাঙ্গুয়েজ ও কণ্ঠস্বর', 'কঠিন কথোপকথন সামলানো'],
                $site.'communication-masterclass-by-tahsan-khan/', $cdn.'skills/thumbnails/communication-masterclass-course-by-tahsan-khan-16x9.jpg'],
            ['career', 'Presentation & Public Speaking', 'Ayman Sadiq', 0, null, true, false, null,
                'মনে রাখার মতো প্রেজেন্টেশন তৈরি ও উপস্থাপনের ফ্রি কোর্স।',
                ['স্লাইডের গঠন', 'স্টেজ ভয় কাটানো', 'ডেলিভারি টেকনিক'],
                $site.'presentation-public-speaking/', $cdn.'thumbnails/skills/presentation-public-speaking-course-thumbnail-by-ayman-sadiq-16_9.jpg'],
            ['career', 'Communication Hacks', 'Sadman Sadik ও Ayman Sadiq', 0, null, true, false, null,
                'শিক্ষার্থী ও তরুণ প্রফেশনালদের জন্য দ্রুত, কাজে লাগার মতো কমিউনিকেশন টিপস।',
                ['স্মল টক ও নেটওয়ার্কিং', 'পরিষ্কার মেসেজ লেখা', 'শোনার দক্ষতা'],
                $site.'communication-hacks/', $cdn.'thumbnails/communication-hacks-course-thumbnail-by-ayman-sadik-sadman-sadik-tahsan-khan.jpg'],
            ['career', 'CV Writing & Interview', 'Ayman Sadiq', 0, null, true, false, null,
                'শর্টলিস্ট হওয়ার মতো CV লিখুন আর ইন্টারভিউয়ে আসলেই যেসব প্রশ্ন হয় তার প্রস্তুতি নিন।',
                ['CV-র গঠন ও ভাষা', 'সাধারণ ইন্টারভিউ প্রশ্ন', 'ফলো-আপের শিষ্টাচার'],
                $site.'cv-writing-interview/', $cdn.'thumbnails/skills/cv-writing-and-interview-skills-course-thumbnail-by-ayman-sadiq-16_9.jpg'],
            // প্রফেশনাল
            ['professional', 'Negotiation Skills', 'Ejazur Rahman', 1250, null, false, false, null,
                'স্পষ্ট ফ্রেমওয়ার্ক দিয়ে বেতন, ডিল আর দৈনন্দিন চুক্তিতে নেগোসিয়েশন করুন।',
                ['নেগোসিয়েশনের প্রস্তুতি', 'অ্যাংকরিং ও ছাড় দেওয়া', 'উভয়পক্ষের জয়ের সমাধান'],
                $site.'negotiation-skills/', $cdn.'thumbnails/skills/Negotiation-Skill-course-thumbnail-by-Ejazur-Rahman-16x9.jpg'],
            ['professional', 'Leadership Excellence', 'Ejazur Rahman', 1250, null, false, false, null,
                'টিম লিড ও ম্যানেজারদের জন্য বাস্তব লিডারশিপ: ডেলিগেশন, ফিডব্যাক আর মোটিভেশন।',
                ['প্রতিদিন টিম চালানো', 'কাজের ফিডব্যাক দেওয়া', 'দ্বন্দ্ব সামলানো'],
                $site.'leadership-excellence/', $cdn.'thumbnails/skills/leadership-excellence-course-thumbnail-by-ejazur-rahman-16x9.jpg'],
            ['professional', 'Money Management', 'Sakib Bin Rashid ও টিম', 0, null, true, false, null,
                'ফ্রি পার্সোনাল ফাইন্যান্স বেসিক: বাজেট, সঞ্চয় আর ঋণের ফাঁদ এড়ানো।',
                ['মাসিক বাজেট', 'সঞ্চয় ও জরুরি তহবিল', 'বুদ্ধিমান খরচের অভ্যাস'],
                $site.'money-management/', $cdn.'thumbnails/money-management-course-thumbnail.jpg'],
            ['professional', 'Digital Financial Mastery', 'Shams Asif Chowdhury ও টিম', 0, null, true, false, null,
                'মোবাইল ফাইন্যান্সিয়াল সার্ভিস নিরাপদে ব্যবহার আর ডিজিটালি টাকা ম্যানেজ করার ফ্রি কোর্স।',
                ['মোবাইল ব্যাংকিং ও পেমেন্ট', 'প্রতারণা থেকে নিরাপদ থাকা', 'ডিজিটাল সঞ্চয়ের টুল'],
                $site.'digital-financial-mastery/', $cdn.'thumbnails/bkash/digital-financial-mastery-thumbnail.jpg'],
            // বান্ডেল
            ['bundles', 'Spoken + Grammar Bundle', 'Munzereen Shahid', 3300, 4450, false, false, 'বান্ডেল',
                'এক দামে দুটি কোর্স: ঘরে বসে Spoken English আর Complete English Grammar Course।',
                ['ঘরে বসে Spoken English', 'Complete English Grammar Course', 'দুটিতেই লাইফটাইম অ্যাক্সেস'],
                $site.'spoken-and-grammar-bundle-course/', $cdn.'thumbnails/spoken-and-grammar-online-course-bundle-thumbnail-new.jpg'],
            ['bundles', "Beginner's English Bundle", $tms, 3750, null, false, false, 'বান্ডেল',
                'আত্মবিশ্বাসের সাথে ইংরেজি বলা ও লেখা শুরু করতে একজন বিগিনারের যা যা দরকার, সব একসাথে।',
                ['Spoken English', 'গ্রামারের ভিত্তি', 'ভোকাবুলারি গড়ে তোলা'],
                $site.'beginners-english-bundle-course/', $cdn.'thumbnails/bundle/beginners_english_bundle_16X9.jpg'],
            // একাডেমিক
            ['class-1-5', 'Spoken English for Kids', 'Munzereen Shahid', 2500, null, false, false, 'কিডস',
                'শিশুদের জন্য মজার স্পোকেন ইংলিশ কোর্স। গল্প, গান আর সহজ কথোপকথন প্র্যাকটিস।',
                ['বয়স উপযোগী লেসন', 'ইন্টারঅ্যাকটিভ অ্যাক্টিভিটি', 'অভিভাবকদের জন্য গাইড'],
                $site.'kids-english/', $cdn.'thumbnails/skills/spoken-english-for-kids-course-thumbnail-by-munzereen-shahid-16x9.jpg'],
            ['class-6', '৬ষ্ঠ শ্রেণি অনলাইন ব্যাচ ২০২৬', $tms, null, null, false, false, 'লাইভ ব্যাচ',
                '৬ষ্ঠ শ্রেণির সারা বছরের অনলাইন ব্যাচ। সব বিষয়ে লাইভ ক্লাস, লেকচার শিট আর নিয়মিত পরীক্ষা।',
                ['প্রতি সপ্তাহে লাইভ ক্লাস', 'অধ্যায়ভিত্তিক লেকচার শিট', 'দৈনিক ও মাসিক পরীক্ষা', 'ডাউট সল্ভিং সাপোর্ট'],
                $site.'class-6-online-batch-2026/', $cdn.'thumbnails/OB_26/class-6-online-batch-26-thumbnail.jpg'],
            ['class-7', '৭ম শ্রেণি অনলাইন ব্যাচ ২০২৬', $tms, null, null, false, false, 'লাইভ ব্যাচ',
                '৭ম শ্রেণির সারা বছরের অনলাইন ব্যাচ। সব বিষয়ে লাইভ ক্লাস, লেকচার শিট আর নিয়মিত পরীক্ষা।',
                ['প্রতি সপ্তাহে লাইভ ক্লাস', 'অধ্যায়ভিত্তিক লেকচার শিট', 'দৈনিক ও মাসিক পরীক্ষা', 'ডাউট সল্ভিং সাপোর্ট'],
                $site.'class-7-online-batch-2026/', $cdn.'thumbnails/OB_26/class-7-online-batch-26-thumbnail.jpg'],
            ['class-8', '৮ম শ্রেণি অনলাইন ব্যাচ ২০২৬', $tms, null, null, false, false, 'লাইভ ব্যাচ',
                '৮ম শ্রেণির সারা বছরের অনলাইন ব্যাচ। সব বিষয়ে লাইভ ক্লাস, লেকচার শিট আর নিয়মিত পরীক্ষা।',
                ['প্রতি সপ্তাহে লাইভ ক্লাস', 'অধ্যায়ভিত্তিক লেকচার শিট', 'দৈনিক ও মাসিক পরীক্ষা', 'ডাউট সল্ভিং সাপোর্ট'],
                $site.'class-8-online-batch-2026/', $cdn.'thumbnails/OB_26/class-8-online-batch-26-thumbnail.jpg'],
            ['ssc', '৯ম শ্রেণি অনলাইন ব্যাচ ২০২৬ (বিজ্ঞান) SSC 28', $tms, null, null, false, true, 'লাইভ ব্যাচ',
                'SSC ২০২৮ পরীক্ষার্থী ৯ম শ্রেণির শিক্ষার্থীদের জন্য বিজ্ঞান বিভাগের অনলাইন ব্যাচ: পদার্থ, রসায়ন, জীববিজ্ঞান ও উচ্চতর গণিত।',
                ['বিজ্ঞানের বিষয়গুলোতে লাইভ ক্লাস', 'লেকচার শিট ও নোট', 'সাপ্তাহিক ও মাসিক পরীক্ষা', 'AI ডাউট সল্ভার'],
                $site.'class-9-online-batch-2026-science-ssc-28/', $cdn.'thumbnails/OB_26/class-9-online-batch-26-thumbnail-ssc-28-science-new.jpg'],
            ['ssc', '৯ম শ্রেণি অনলাইন ব্যাচ ২০২৬ (বাংলা, ইংরেজি ও ICT) SSC 28', $tms, null, null, false, false, 'লাইভ ব্যাচ',
                'SSC ২০২৮ এর প্রস্তুতি নেওয়া ৯ম শ্রেণির শিক্ষার্থীদের জন্য বাংলা, ইংরেজি ও ICT অনলাইন ব্যাচ।',
                ['লাইভ ক্লাস', 'বিষয়ভিত্তিক লেকচার শিট', 'নিয়মিত পরীক্ষা'],
                $site.'class-9-online-batch-2026-bangla-english-ict-ssc-28/', $cdn.'thumbnails/OB_26/class-9-online-batch-26-thumbnail-ssc-28-bangla-english-ict.jpg'],
            ['ssc', 'SSC 27 বোর্ড পরীক্ষা প্রস্তুতি (বিজ্ঞান বিভাগ)', $tms, null, null, false, false, 'লাইভ ব্যাচ',
                'SSC ২০২৭ বিজ্ঞান বিভাগের শিক্ষার্থীদের বোর্ড পরীক্ষার প্রস্তুতি। লাইভ ক্লাস, মডেল টেস্ট আর রিভিশন।',
                ['পুরো সিলেবাস কভার', 'মডেল টেস্ট', 'পরীক্ষার আগে রিভিশন ক্লাস'],
                $site.'class-10-online-batch-2026-science-ssc-27/', $cdn.'thumbnails/ssc-27/ssc-27-board-exam-preparation-thumbnail_optimized_5000.png'],
            ['ssc', '১০ম শ্রেণি অনলাইন ব্যাচ ২০২৬ (বাংলা, ইংরেজি ও ICT) SSC 27', $tms, null, null, false, false, 'লাইভ ব্যাচ',
                'SSC ২০২৭ এর প্রস্তুতি নেওয়া ১০ম শ্রেণির শিক্ষার্থীদের জন্য বাংলা, ইংরেজি ও ICT অনলাইন ব্যাচ।',
                ['লাইভ ক্লাস', 'বিষয়ভিত্তিক লেকচার শিট', 'নিয়মিত পরীক্ষা'],
                $site.'class-10-online-batch-2026-bangla-english-ict-ssc-27/', $cdn.'thumbnails/OB_26/class-10-online-batch-26-thumbnail-ssc-27-bangla-english-ict.jpg'],
            ['hsc', 'HSC 27 সায়েন্স গ্রুপ অনলাইন ব্যাচ', $tms, null, null, false, true, 'লাইভ ব্যাচ',
                'HSC ২০২৭ এর বিজ্ঞানের চারটি বিষয় এক ব্যাচে: ফিজিক্স, কেমিস্ট্রি, উচ্চতর গণিত ও বায়োলজি। প্রতি সপ্তাহে ১২টি লাইভ ক্লাস।',
                ['প্রতি সপ্তাহে ১২টি লাইভ ক্লাস', 'দৈনিক, সাপ্তাহিক ও মাসিক পরীক্ষা', 'AI ডাউট সল্ভার', 'প্রতিটি বিষয়ের মাস্টার বুক'],
                $site.'hsc-27-science-group-online-batch/', $cdn.'thumbnails/HSC_OB_27/hsc-2027-online-batch-science-group-thumbnail-new.png'],
            ['hsc', 'HSC 27 ফিজিক্স অনলাইন ব্যাচ', $tms, null, null, false, false, 'লাইভ ব্যাচ',
                'HSC ২০২৭ এর ফিজিক্স অনলাইন ব্যাচ। প্রতি সপ্তাহে ৩টি লাইভ ক্লাস, পরীক্ষা আর ডাউট সল্ভিং।',
                ['প্রতি সপ্তাহে ৩টি লাইভ ক্লাস', 'অধ্যায়ভিত্তিক পরীক্ষা', 'AI ডাউট সল্ভার'],
                $site.'hsc-27-physics-online-batch/', $cdn.'thumbnails/HSC_OB_27/hsc-27-physics-online-batch-thumbnail-new.png'],
            ['hsc', 'HSC 27 কেমিস্ট্রি অনলাইন ব্যাচ', $tms, null, null, false, false, 'লাইভ ব্যাচ',
                'HSC ২০২৭ এর কেমিস্ট্রি অনলাইন ব্যাচ। প্রতি সপ্তাহে ৩টি লাইভ ক্লাস, পরীক্ষা আর ডাউট সল্ভিং।',
                ['প্রতি সপ্তাহে ৩টি লাইভ ক্লাস', 'অধ্যায়ভিত্তিক পরীক্ষা', 'AI ডাউট সল্ভার'],
                $site.'hsc-27-chemistry-online-batch/', $cdn.'thumbnails/HSC_OB_27/hsc-27-chemistry-online-batch-thumbnail.png'],
            ['hsc', 'HSC 27 ম্যাথ অনলাইন ব্যাচ', $tms, null, null, false, false, 'লাইভ ব্যাচ',
                'HSC ২০২৭ এর উচ্চতর গণিত অনলাইন ব্যাচ। প্রতি সপ্তাহে ৩টি লাইভ ক্লাস, পরীক্ষা আর ডাউট সল্ভিং।',
                ['প্রতি সপ্তাহে ৩টি লাইভ ক্লাস', 'অধ্যায়ভিত্তিক পরীক্ষা', 'AI ডাউট সল্ভার'],
                $site.'hsc-27-math-online-batch/', $cdn.'thumbnails/HSC_OB_27/hsc-27-math-online-batch-thumbnail.png'],
            ['hsc', 'HSC 27 বায়োলজি অনলাইন ব্যাচ', $tms, null, null, false, false, 'লাইভ ব্যাচ',
                'HSC ২০২৭ এর বায়োলজি অনলাইন ব্যাচ। প্রতি সপ্তাহে ৩টি লাইভ ক্লাস, পরীক্ষা আর ডাউট সল্ভিং।',
                ['প্রতি সপ্তাহে ৩টি লাইভ ক্লাস', 'অধ্যায়ভিত্তিক পরীক্ষা', 'AI ডাউট সল্ভার'],
                $site.'hsc-27-biology-online-batch/', $cdn.'thumbnails/HSC_OB_27/hsc-27-biology-online-batch-thumbnail.png'],
            ['hsc', 'HSC 27 বাংলা, ইংরেজি ও ICT অনলাইন ব্যাচ', $tms, null, null, false, false, 'লাইভ ব্যাচ',
                'HSC ২০২৭ এর বাংলা, ইংরেজি ও ICT। প্রতি বিষয়ে সপ্তাহে ২টি লাইভ ক্লাস আর বিষয়ভিত্তিক মাস্টার বুক।',
                ['প্রতি বিষয়ে সপ্তাহে ২টি লাইভ ক্লাস', 'মাস্টার বুক সহ', 'দৈনিক, সাপ্তাহিক ও মাসিক পরীক্ষা'],
                $site.'hsc-27-online-batch-2-bangla-english-ict/', $cdn.'thumbnails/HSC_OB_27/hsc-27-bangla-english-ict-online-batch-thumbnail-updated.jpg'],
            ['hsc', 'HSC Physics Foundation Course', $tms, 0, null, true, false, null,
                'ব্যাচ শুরুর আগে HSC ফিজিক্সের মূল ধারণাগুলো ঝালিয়ে নেওয়ার ফ্রি ফাউন্ডেশন কোর্স।',
                ['ফিজিক্সের মূল ধারণা', 'সমাধানসহ উদাহরণ', 'প্র্যাকটিস প্রশ্ন'],
                $site.'hsc-physics-foundation-course/', $cdn.'thumbnails/hsc-physics-foundation-course-thumbnail-new.png'],
            ['hsc', 'HSC 27 ফাউন্ডেশন কোর্স (বাংলা, ইংরেজি ও ICT)', $tms, 0, null, true, false, null,
                'HSC ২০২৭ শুরু করা শিক্ষার্থীদের জন্য বাংলা, ইংরেজি ও ICT-র ফ্রি ফাউন্ডেশন লেসন।',
                ['প্রতিটি বিষয়ের বেসিক', 'রেকর্ডেড লেসন', 'প্র্যাকটিস সেট'],
                $site.'hsc-27-bangla-english-ict-foundation-course/', $cdn.'thumbnails/hsc-27-bangla-english-ict-foundation-course-thumbnail.png'],
            ['admission', 'ভার্সিটি A Unit + গুচ্ছ এডমিশন কোর্স ২০২৬', $tms, 5000, null, false, false, null,
                'বিজ্ঞান ইউনিটের বিশ্ববিদ্যালয় ভর্তি পরীক্ষা আর গুচ্ছ পরীক্ষার সম্পূর্ণ প্রস্তুতি।',
                ['বিষয়ভিত্তিক লাইভ ক্লাস', 'প্রশ্নব্যাংক ও মডেল টেস্ট', 'এডমিশন স্ট্র্যাটেজি সেশন'],
                $site.'varsity-a-unit-and-gst-admission-course-2026/', $cdn.'thumbnails/Admission_2026/varsity-a-unit-and-gst-admission-course-2026-thumbnail.png'],
            ['admission', 'ভার্সিটি B Unit + গুচ্ছ এডমিশন কোর্স ২০২৬', $tms, 4500, null, false, false, null,
                'মানবিক ইউনিটের বিশ্ববিদ্যালয় ভর্তি পরীক্ষা আর গুচ্ছ পরীক্ষার সম্পূর্ণ প্রস্তুতি।',
                ['বিষয়ভিত্তিক লাইভ ক্লাস', 'প্রশ্নব্যাংক ও মডেল টেস্ট', 'এডমিশন স্ট্র্যাটেজি সেশন'],
                $site.'varsity-b-unit-and-gst-admission-course-2026/', $cdn.'thumbnails/Admission_2026/varsity-b-unit-and-gst-admission-course-2026-thumbnail.png'],
            ['admission', 'ভার্সিটি C Unit + গুচ্ছ এডমিশন কোর্স ২০২৬', $tms, 4500, null, false, false, null,
                'ব্যবসায় শিক্ষা ইউনিটের বিশ্ববিদ্যালয় ভর্তি পরীক্ষা আর গুচ্ছ পরীক্ষার সম্পূর্ণ প্রস্তুতি।',
                ['বিষয়ভিত্তিক লাইভ ক্লাস', 'প্রশ্নব্যাংক ও মডেল টেস্ট', 'এডমিশন স্ট্র্যাটেজি সেশন'],
                $site.'varsity-c-unit-and-gst-admission-course-2026/', $cdn.'thumbnails/Admission_2026/varsity-c-unit-and-gst-admission-course-2026-thumbnail.png'],
        ];

        foreach ($courses as $i => [$cat, $title, $instructor, $price, $original, $free, $featured, $badge, $description, $highlights, $url, $image]) {
            $slug = basename(parse_url($url, PHP_URL_PATH));
            $existing = Course::where('affiliate_url', $url)->first();
            $payload = [
                'category_id' => $categories[$cat]->id,
                'title' => $title,
                'instructor' => $instructor,
                'price' => $price,
                'original_price' => $original,
                'is_free' => $free,
                'is_featured' => $featured,
                'badge' => $badge,
                'description' => $description,
                'highlights' => $highlights,
                'affiliate_url' => $url,
                'image' => $image,
                'is_published' => true,
                'sort_order' => $i,
            ];
            if ($existing) {
                $existing->update($payload);
            } else {
                Course::create($payload + ['slug' => $slug]);
            }
        }
    }
}
